name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-platform
            docker stop myapp || true
            docker rm myapp || true
            docker build -t devops-platform .
            docker run -d --name myapp -p 5000:5000 devops-platform
            echo "Deployed successfully!"